# gateway-sidecar
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storj-s3-gateway-deployment
  labels:
    app: s3-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-gateway
  template:
    metadata:
      labels:
        app: s3-gateway
    spec:
      containers:
      - name: gateway
        image: storjlabs/gateway:b8e4299-v1.1.0-go1.13.8
        ports:
        - containerPort: 7777
