apiVersion: v1
kind: Service
metadata:
  name: s3-gateway-svc
spec:
  selector:
    app: {{ .Values.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
